services:
  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    env_file:
      - config/app.env
    network_mode: host
    restart: unless-stopped
    command: ["node", "apps/api/dist/src/server.js"]

  worker:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    env_file:
      - config/worker.env
    network_mode: host
    restart: unless-stopped
    command: ["node", "apps/api/dist/src/worker/run-worker.js"]
